package com.techprimers.elastic;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

// Was it generated by Spring Initializr ?!
@RunWith(SpringRunner.class)
@SpringBootTest
public class SpringElasticDemoApplicationTests {

	@Test
	public void contextLoads() {
	}

}
